
--Repeat vs One-Time Customers

SELECT CUSTOMER_TYPE,
	   COUNT(*) TOTAL_CUSTOMERS

FROM (

SELECT 
CASE
	WHEN COUNT(O.ORDER_ID) = 0 THEN 'NO ORDERS'
	WHEN COUNT(O.ORDER_ID) = 1 THEN 'ONE-TIME CUSTOMERS'
	ELSE 'REPEAT CUSTOMERS'
END AS CUSTOMER_TYPE

FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID

GROUP BY C.CUSTOMER_ID

) SUB


GROUP BY CUSTOMER_TYPE






--Top Customers by Spending


SELECT C.CUSTOMER_ID,
	   SUM(OP.PAYMENT_VALUE) AS TOTAL_SPEND


FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_PAYMENTS OP
ON O.ORDER_ID = OP.ORDER_ID

GROUP BY C.CUSTOMER_ID

ORDER BY TOTAL_SPEND DESC
LIMIT 10



--CUSTOMER LIFE TIME VALUE



SELECT C.CUSTOMER_ID,
	   SUM(OP.PAYMENT_VALUE) AS LIFE_TIME_VALUE


FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_PAYMENTS OP
ON O.ORDER_ID = OP.ORDER_ID

GROUP BY C.CUSTOMER_ID

ORDER BY LIFE_TIME_VALUE DESC



--CUSTOMER PURCHASE FREQUENCY 


SELECT C.CUSTOMER_ID,
	   COUNT(O.ORDER_ID) AS TOTAL_ORDERS


FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID

GROUP BY C.CUSTOMER_ID




--Customer Distribution by State


SELECT CUSTOMER_STATE_FULLNAME,
	   COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS

FROM CUSTOMERS 

GROUP BY CUSTOMER_STATE_FULLNAME

