

--Top Selling Products


SELECT P.PRODUCT_ID,
	   COUNT(O.ORDER_ID) AS TOTAL_ORDERS


FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
ON OI.ORDER_ID = O.ORDER_ID


GROUP BY P.PRODUCT_ID

ORDER BY TOTAL_ORDERS DESC
LIMIT 10



--Best Selling Product Categories


SELECT PRODUCT_CATEGORY_NAME_ENGLISH,
	   COUNT(O.ORDER_ID) AS TOTAL_ORDERS

FROM PRODUCT_CATEGORY PC
JOIN PRODUCTS P
ON PC.PRODUCT_CATEGORY_NAME = P.PRODUCT_CATEGORY_NAME
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
ON OI.ORDER_ID = O.ORDER_ID

GROUP BY PRODUCT_CATEGORY_NAME_ENGLISH

ORDER BY TOTAL_ORDERS DESC
LIMIT 10





--Revenue by Product Category



SELECT PRODUCT_CATEGORY_NAME_ENGLISH,
	   SUM(OP.PAYMENT_VALUE) AS TOTAL_REVENUE

FROM PRODUCT_CATEGORY PC
JOIN PRODUCTS P
ON PC.PRODUCT_CATEGORY_NAME = P.PRODUCT_CATEGORY_NAME
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDERS O
ON OI.ORDER_ID = O.ORDER_ID
JOIN ORDER_PAYMENTS OP
ON O.ORDER_ID = OP.ORDER_ID

GROUP BY PRODUCT_CATEGORY_NAME_ENGLISH

ORDER BY TOTAL_REVENUE DESC
LIMIT 10


--Average Product Price by Category


SELECT PC.PRODUCT_CATEGORY_NAME_ENGLISH,
	   AVG(OI.PRICE) AS AVG_PRODUCT_CATEGORY_PRICE



FROM PRODUCT_CATEGORY PC
JOIN PRODUCTS P
ON PC.PRODUCT_CATEGORY_NAME = P.PRODUCT_CATEGORY_NAME
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID

GROUP BY PC.PRODUCT_CATEGORY_NAME_ENGLISH

ORDER BY AVG_PRODUCT_CATEGORY_PRICE DESC

LIMIT 10;


