


--Review Score Distribution


SELECT REVIEW_SCORE,
	   COUNT(REVIEW_ID) AS TOTAL_REVIEWS


FROM ORDER_REVIEWS

GROUP BY REVIEW_SCORE



--Average Review Score

SELECT AVG(REVIEW_SCORE) AS AVG_REVIEW


FROM ORDER_REVIEWS



--Delivery Delay Impact on Reviews


SELECT O.ORDER_ID,
	   DATE_PART('DAY',O.ORDER_DELIVERED_CUSTOMER_DATE - ORDER_ESTIMATED_DELIVERY_DATE) AS DELIVERY_DELAY,
	   ORE.REVIEW_SCORE


FROM ORDERS O
JOIN ORDER_REVIEWS ORE
ON O.ORDER_ID = ORE.ORDER_ID

WHERE O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL


--Average Review Score by Product Category


SELECT PC.PRODUCT_CATEGORY_NAME_ENGLISH,
	   AVG(REVIEW_SCORE) AS AVG_REVIEW_SCORE


FROM PRODUCT_CATEGORY PC
JOIN PRODUCTS P
ON PC.PRODUCT_CATEGORY_NAME = P.PRODUCT_CATEGORY_NAME
JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
JOIN ORDER_REVIEWS R
ON OI.ORDER_ID = R.ORDER_ID


GROUP BY PC.PRODUCT_CATEGORY_NAME_ENGLISH

ORDER BY AVG_REVIEW_SCORE DESC
LIMIT 10


--REVIEWS OVER TIME

SELECT DATE_TRUNC('MONTH',REVIEW_CREATION_DATE) AS REVIEW_MONTH,
	   AVG(REVIEW_SCORE) AS AVG_REVIEW_SCORE


FROM ORDER_REVIEWS 

GROUP BY DATE_TRUNC('MONTH',REVIEW_CREATION_DATE)

ORDER BY REVIEW_MONTH




