

--Top Sellers by Revenue

 
SELECT S.SELLER_ID,
	   ROUND(SUM(OP.PAYMENT_VALUE)::NUMERIC,2) AS TOTAL_REVENUE


FROM SELLERS S
JOIN ORDER_ITEMS OI
ON S.SELLER_ID = OI.SELLER_ID
JOIN ORDER_PAYMENTS OP
ON OI.ORDER_ID = OP.ORDER_ID

GROUP BY S.SELLER_ID
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


--Sellers by State


SELECT SELLER_STATE_FULLNAME,
	   COUNT(SELLER_ID) AS TOTAL_SELLERS


FROM SELLERS

GROUP BY SELLER_STATE_FULLNAME

ORDER BY TOTAL_SELLERS DESC
LIMIT 10;


--Seller Sales Volume


SELECT S.SELLER_ID,
	   COUNT(O.ORDER_ID) AS TOTAL_ORDERS
 

FROM SELLERS S
JOIN ORDER_ITEMS OI
ON S.SELLER_ID = OI.SELLER_ID
JOIN ORDERS O
ON OI.ORDER_ID = O.ORDER_ID

GROUP BY S.SELLER_ID
ORDER BY TOTAL_ORDERS DESC
LIMIT 10;



--Seller Average Product Price


SELECT S.SELLER_ID,
	   ROUND(AVG(OI.PRICE)::NUMERIC,2) AS AVERAGE_PRICE


FROM SELLERS S
JOIN ORDER_ITEMS OI
ON S.SELLER_ID = OI.SELLER_ID

GROUP BY S.SELLER_ID
ORDER BY AVERAGE_PRICE DESC
LIMIT 10;




--Seller Delivery Performance


WITH AVERAGE_DELIVERY_DAYS AS (

SELECT OI.SELLER_ID,
	   ROUND(AVG(
	     DATE_PART('DAY',O.ORDER_DELIVERED_CUSTOMER_DATE - O.ORDER_PURCHASE_TIMESTAMP::TIMESTAMP)
	   )::NUMERIC,2) AS AVG_DELIVERY_DAYS


FROM ORDER_ITEMS OI
JOIN ORDERS O
ON OI.ORDER_ID = O.ORDER_ID

WHERE O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL

GROUP BY OI.SELLER_ID
ORDER BY AVG_DELIVERY_DAYS


)

,DELIVERY_STATUS_CTE AS (

SELECT *,
CASE
	WHEN AVG_DELIVERY_DAYS <= 2 THEN 'FAST DELIVERY'
	WHEN AVG_DELIVERY_DAYS BETWEEN 3 AND 4 THEN 'MEDIUM DELIVERY'
	WHEN AVG_DELIVERY_DAYS BETWEEN 4 AND 6 THEN 'SLOW DELIVERY' 
	ELSE 'VERY SLOW DELIVERY'
END AS DELIVERY_STATUS

FROM AVERAGE_DELIVERY_DAYS

)
SELECT DELIVERY_STATUS,
	   COUNT(SELLER_ID) AS TOTAL_SELLERS


FROM DELIVERY_STATUS_CTE

GROUP BY DELIVERY_STATUS


